### ISSUE TITLE
A CONTRIBUTING.md file

### ISSUE THREAD

**Issue by jalalbmnf** [stylify/packages#143]
Hi @Machy8 can you create A CONTRIBUTING.md file cause it helps who wants to contribute stylify for how to configure repository also what are requirements and etc.

**Comment by Machy8** [comment]
@jalalbmnf I will look into it. Thanks for mentioning that the file is missing!

**Comment by jalalbmnf** [comment]
Thank you for response. After this file i can start to contribute , cause also i need to know how to configure this repo , if here have any requirement :)

**Comment by jalalbmnf** [comment]
> @jalalbmnf Hi, could you please check, if #149 the notes in this repo work for you and makes sense to you as a possible new contributor?

Hi @Machy8 , i guess that's okay. Thank you so much 👍🏼

**Comment by Machy8** [comment]
@jalalbmnf Thanks! Merging. In case, something is missing, let me know.
