### ISSUE TITLE
Add support for vite 4

### ISSUE THREAD

**Issue by CiprianN23** [stylify/packages#163]
### Describe the problem

Added stylify to a sveltekit 1.0 project and got prompted with

``` WARN  Issues with peer dependencies found

└─┬ @stylify/unplugin 0.5.10
  └─┬ unplugin 0.8.1
    └── ✕ unmet peer vite@"^2.3.0 || ^3.0.0-0": found 4.0.3

```

### Describe the proposed solution

-

### Alternatives considered

-

### Importance

nice to have

**Comment by Machy8** [comment]
Hi @CiprianN23.

Thanks for the issue, I will look into it.

**Comment by Machy8** [comment]
@CiprianN23 
Hi! Can you please try, if the error still appears? Stylify 0.5.11 have been updated to the latest Unplugin that should support Vite 4.0.

**Comment by CiprianN23** [comment]
> @CiprianN23 Hi! Can you please try, if the error still appears? Stylify 0.5.11 have been updated to the latest Unplugin that should support Vite 4.0. In my testing, it seems ok.

Yes it fine now , thank you!

**Comment by Machy8** [comment]
Great. Thanks for the response. If you find any more issues, let me know!
