### ISSUE TITLE
Css variables should be enabled by default

### ISSUE THREAD

**Issue by Machy8** [stylify/packages#195]
### Describe the problem

The support seems fine https://caniuse.com/?search=css%20variables 

### Describe the proposed solution

Just set the false to true

### Alternatives considered

.

### Importance

would make my life easier

**Comment by MilesPernicious** [comment]
If you are going to change this anyway, might I also suggest changing the name?

The current name is rather long and not grammatically correct English.

`enableCssVariables` or even `useCssVariables` would be cleaner looking.

**Comment by Machy8** [comment]
Hi @MilesPernicious. Thanks for this comment.

A good idea. I was also thinking about `enableCssVariables`.

With this following BC break, this option will be for disabling CSS variables . So maybe `cssVariablesEnabled`?:
```js
const config = {
   enableCssVariables: false,
   // Or
   cssVariablesEnabled: false
}
```
