### ISSUE TITLE
Macro matching fails in some cases

### ISSUE THREAD

**Issue by MilesPernicious** [stylify/packages#221]
### Describe the bug

Machy8: No, it collides with "x"  and "y" property that is used on svgs. But it is matched before your macro and therefore your macro is not matched. The order of matching is incorrect.

### Reproduction

```JavaScript
            'padding-y:(\\S+?)': ({ macroMatch, selectorProperties }) => {
                selectorProperties.add('padding-top', macroMatch.getCapture(0));
                selectorProperties.add('padding-bottom', macroMatch.getCapture(0));
            },
```

`class="padding-y:2rem"`

```CSS
/* stylify.css */
.y\:2rem{
    y: 2rem
}
```

### System Info

```shell
@stylify/astro 0.5.28
```

**Comment by Machy8** [comment]
@MilesPernicious This should be fixed in 0.5.33.
